import { NavLink } from 'react-router-dom'
import { mockRepository as repo } from '../../data/mockRepository'
import { toDateKey } from '../../domain/availability'
import { Badge, Button, Card, Empty, Logo } from '../../design-system/ui'
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const menus=[['/painel','Início'],['/painel/agenda','Agenda'],['/painel/profissionais','Profissionais'],['/painel/servicos','Serviços'],['/painel/clientes','Clientes'],['/painel/relatorios','Relatórios']]
export function ProviderLayout({children}:{children:React.ReactNode}){return <div className="provider"><aside className="sidebar"><Logo/><nav>{menus.map(([path,label])=><NavLink key={path} to={path} end={path==='/painel'}>{label}</NavLink>)}</nav></aside><main className="main">{children}</main></div>}
function Upcoming(){const appts=repo.getAppointments(),services=repo.getServices(),people=repo.getProfessionals(),customers=repo.getCustomers();return <Card><h2>Próximos atendimentos</h2>{appts.map(a=>{const s=services.find(x=>x.id===a.serviceId)!,p=people.find(x=>x.id===a.professionalId)!,c=customers.find(x=>x.id===a.customerId)!;return <article className="appointment" key={a.id}><time>{new Date(a.start).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time><div className="info"><strong>{c.name}</strong><p>{s.name} · {p.name}</p></div><Badge status={a.status}/></article>})}</Card>}
export function Dashboard(){const appts=repo.getAppointments(),services=repo.getServices(),today=toDateKey(new Date());const todayAppts=appts.filter(a=>a.start.startsWith(today));const confirmed=appts.filter(a=>a.status==='Confirmado');const revenue=confirmed.reduce((sum,a)=>sum+(services.find(s=>s.id===a.serviceId)?.price??0),0);return <><header className="topbar"><div><p className="muted">Visão geral</p><h1>Olá, equipe Aurora</h1></div><Button>Novo agendamento</Button></header><div className="metric-grid">{[['Agendamentos hoje',todayAppts.length],['Confirmados',confirmed.length],['Faturamento previsto',money(revenue)],['Aguardando confirmação',appts.filter(a=>a.status==='Aguardando confirmação').length]].map(([label,value])=><Card className="metric" key={String(label)}><span className="muted">{label}</span><strong>{value}</strong></Card>)}</div><section className="section"><Upcoming/></section></>}
export function Agenda(){const appts=repo.getAppointments(),services=repo.getServices(),people=repo.getProfessionals(),customers=repo.getCustomers();const dates=Array.from({length:5},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return toDateKey(d)});return <><header className="topbar"><div><p className="muted">Semana atual</p><h1>Agenda</h1></div><select aria-label="Filtrar por profissional"><option>Todos os profissionais</option>{people.map(p=><option key={p.id}>{p.name}</option>)}</select></header><Card><p className="muted">Legenda: <Badge status="Confirmado"/> <Badge status="Aguardando confirmação"/></p><div className="week"><div className="week-grid"><div className="dayhead">Hora</div>{dates.map(d=><div className="dayhead" key={d}>{new Date(`${d}T12:00`).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'})}</div>)}{['09:00','10:00','11:00','13:00','14:00','15:00','16:00','17:00'].flatMap(time=>[<div className="slot" key={`${time}-time`}>{time}</div>,...dates.map(d=>{const appt=appts.find(a=>a.start.startsWith(`${d}T${time}`));if(!appt)return <div className="slot" key={`${d}-${time}`}/>;const c=customers.find(x=>x.id===appt.customerId)!,s=services.find(x=>x.id===appt.serviceId)!;return <div className="slot" key={`${d}-${time}`} title={`${c.name} — ${s.name}`}><strong>{c.name}</strong><br/>{s.name}</div>})])}</div></div></Card></>}
export function FutureModule(){return <><header className="topbar"><h1>Módulo em preparação</h1></header><Empty>Esta prévia não inclui CRUD ou relatórios fictícios. O módulo será construído em uma próxima etapa.</Empty></>}
