import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { mockRepository as repo } from '../../data/mockRepository'
import { addDays, availableTimes, professionalsForService, toDateKey } from '../../domain/availability'
import type { BookingChoice } from '../../domain/models'
import { Button, Card, Field, Steps } from '../../design-system/ui'
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function EstablishmentPage(){const e=repo.getEstablishment(),services=repo.getServices();return <><header className="public-header"><div className="container"><Link to="/"><strong>agendaJá</strong></Link><Link to="/login">Área do prestador</Link></div></header><main><section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Agendamento simples e acolhedor</span><h1>{e.name}</h1><p>{e.category} · {e.address}</p><p>★ {e.rating.toLocaleString('pt-BR')} <small>(avaliação de demonstração)</small></p><Link to="/agendar"><Button>Fazer agendamento</Button></Link></div><div className="hero-art" aria-hidden="true">✦</div></div></section><section className="section container"><h2>Serviços e horários</h2><p className="muted">{e.hours}</p><div className="service-grid">{services.map(s=><Card className="service" key={s.id}><div><strong>{s.name}</strong><p className="muted">{s.duration} min</p></div><strong>{money(s.price)}</strong></Card>)}</div></section></main></>}
export function Booking(){const [step,setStep]=useState(1),[choice,setChoice]=useState<BookingChoice>({});const services=repo.getServices(),professionals=repo.getProfessionals();const service=services.find(s=>s.id===choice.serviceId);const availableProfessionals=service?professionalsForService(professionals,service.id):[];const selectedProfessional=professionals.find(p=>p.id===choice.professionalId);const dates=Array.from({length:6},(_,i)=>toDateKey(addDays(new Date(),i+1)));const times=useMemo(()=>service&&selectedProfessional&&choice.date?availableTimes(choice.date,selectedProfessional,service,repo.getAppointments(),services):[],[service,selectedProfessional,choice.date,services]);const go=(n:number)=>setStep(n)
 function selectService(id:string){setChoice({serviceId:id});go(2)} function selectProfessional(id:string){setChoice(c=>({...c,professionalId:id,date:undefined,time:undefined}));go(3)}
 if(step===5&&service&&selectedProfessional&&choice.customer)return <main className="booking container"><div className="booking-main"><Card className="confirmation"><p className="eyebrow">Agendamento de demonstração</p><h1>Pedido preparado!</h1><p>Nenhum horário foi reservado no servidor e nenhuma notificação foi enviada.</p><div className="summary"><strong>{service.name} · {money(service.price)}</strong><span>{selectedProfessional.name}</span><span>{new Date(`${choice.date}T${choice.time}`).toLocaleString('pt-BR',{dateStyle:'full',timeStyle:'short'})}</span></div><Link to="/"><Button variant="secondary">Voltar ao estabelecimento</Button></Link></Card></div></main>
 return <main className="booking container"><div className="booking-main"><Link to="/">← Ateliê Aurora</Link><h1>Fazer agendamento</h1><Steps step={step}/>{step===1&&<Card><h2>Escolha o serviço</h2>{services.map(s=><button className={`option ${choice.serviceId===s.id?'selected':''}`} onClick={()=>selectService(s.id)} key={s.id}><span><strong>{s.name}</strong><br/><small>{s.duration} min</small></span><strong>{money(s.price)}</strong></button>)}</Card>}{step===2&&<Card><h2>Escolha o profissional</h2><button className="option" onClick={()=>availableProfessionals[0]&&selectProfessional(availableProfessionals[0].id)}><span><strong>Qualquer profissional</strong><br/><small>Escolhemos alguém disponível</small></span></button>{availableProfessionals.length?availableProfessionals.map(p=><button className={`option ${choice.professionalId===p.id?'selected':''}`} onClick={()=>selectProfessional(p.id)} key={p.id}><span><strong>{p.name}</strong><br/><small>{p.specialties.join(', ')}</small></span></button>):<p>Nenhum profissional atende este serviço.</p>}<Button variant="ghost" onClick={()=>go(1)}>Voltar</Button></Card>}{step===3&&<Card><h2>Data e horário</h2><div className="filters">{dates.map(d=><Button variant={choice.date===d?'primary':'secondary'} key={d} onClick={()=>setChoice(c=>({...c,date:d,time:undefined}))}>{new Date(`${d}T12:00`).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'})}</Button>)}</div>{choice.date&&<><div className="filters"><span className="muted">Manhã · Tarde · Noite</span></div><div className="time-grid">{times.map(t=><button className={choice.time===t?'selected':''} key={t} onClick={()=>setChoice(c=>({...c,time:t}))}>{t}</button>)}</div>{!times.length&&<p className="notice">Não há horários disponíveis nesta data.</p>}</>}<div className="form-actions"><Button variant="ghost" onClick={()=>go(2)}>Voltar</Button><Button disabled={!choice.time} onClick={()=>go(4)}>Continuar</Button></div></Card>}{step===4&&<Card><h2>Seus dados</h2><p className="notice">Usaremos estes dados somente nesta demonstração. O cadastro será integrado ao backend futuramente.</p><form className="form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);setChoice(c=>({...c,customer:{name:String(form.get('name')),phone:String(form.get('phone')),email:String(form.get('email'))}}));go(5)}}><Field name="name" label="Nome completo" required/><Field name="phone" label="Telefone / WhatsApp" inputMode="tel" required/><Field name="email" label="E-mail" type="email" required/><div className="form-actions"><Button type="button" variant="ghost" onClick={()=>go(3)}>Voltar</Button><Button>Revisar agendamento</Button></div></form></Card>}</div></main>}
